[package]
name = "zstdscope-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
zstdscope = { path = "../crates/zstdscope" }

[[bin]]
name = "inspect"
path = "fuzz_targets/inspect.rs"
test = false
doc = false
bench = false
